# Generated by Django 4.2.9 on 2024-10-28 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_task', models.TextField(verbose_name='задание для дз')),
                ('materials', models.FileField(upload_to='homeworks')),
            ],
            options={
                'verbose_name': 'домашнее задание',
                'verbose_name_plural': 'домашние задания',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='дата сдачи')),
                ('submission_time', models.TimeField(auto_now_add=True, verbose_name='время сдачи')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework_submissions', verbose_name='файл сдачи')),
                ('is_completed', models.BooleanField(default=False, verbose_name='выполнено')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.homework', verbose_name='задание для дз')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'сдача дз',
                'verbose_name_plural': 'сдачи дз',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка к дз')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('homework_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.homeworksubmission', verbose_name='сдача дз')),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'оценки',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='название')),
                ('date_of_lesson', models.DateField(verbose_name='дата урока')),
                ('time_of_lesson', models.TimeField(verbose_name='время урока')),
                ('homeworks', models.ManyToManyField(blank=True, to='account.homework', verbose_name='Д/З урока')),
                ('students', models.ManyToManyField(blank=True, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='ученики')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.mark', verbose_name='оценка'),
        ),
    ]
