# Generated by Django 4.2.9 on 2024-10-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
