# Generated by Django 4.2.9 on 2025-01-12 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_lessons_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='ученики'),
        ),
    ]
